"""add employee table

Revision ID: 04a6f82c5654
Revises: d7db96f2301a
Create Date: 2023-08-16 10:32:30.285157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a6f82c5654'
down_revision: Union[str, None] = 'd7db96f2301a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('med_times', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_med_times_signed_off_user'), 'user', ['signed_off'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('med_times', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_med_times_signed_off_user'), type_='foreignkey')

    op.drop_table('user')
    # ### end Alembic commands ###
