"""modified tables

Revision ID: 3bc3b5b5336d
Revises: 5d79bde352ff
Create Date: 2023-08-14 21:57:47.813507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc3b5b5336d'
down_revision: Union[str, None] = '5d79bde352ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'doctor_id')
    op.add_column('doctors', sa.Column('name', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('name', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('medication_use', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('med_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'med_type')
    op.drop_column('medications', 'medication_use')
    op.drop_column('medications', 'name')
    op.drop_column('doctors', 'phone_number')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'name')
    op.add_column('clients', sa.Column('doctor_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
