"""fix client medication relationship 

Revision ID: 82ffd046e21e
Revises: a339764f02c9
Create Date: 2023-08-15 20:04:42.457607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ffd046e21e'
down_revision: Union[str, None] = 'a339764f02c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clent_medication')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clent_medication',
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('medication_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_clent_medication_client_id_clients'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name='fk_clent_medication_medication_id_medications'),
    sa.PrimaryKeyConstraint('client_id', 'medication_id')
    )
    # ### end Alembic commands ###
