"""add med client table

Revision ID: 8ba20337b2d6
Revises: 3bc3b5b5336d
Create Date: 2023-08-15 13:50:30.641639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba20337b2d6'
down_revision: Union[str, None] = '3bc3b5b5336d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clent_medication',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'medication_id')
    )
    op.create_table('med_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(), nullable=True),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('signed_off', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('med_times')
    op.drop_table('clent_medication')
    # ### end Alembic commands ###
