"""add columns to all tables"

Revision ID: a171eeb3e1df
Revises: b93a10b3e6b1
Create Date: 2023-08-14 20:26:30.760035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a171eeb3e1df'
down_revision: Union[str, None] = 'b93a10b3e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('name', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('name', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('medication_use', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('med_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'med_type')
    op.drop_column('medications', 'medication_use')
    op.drop_column('medications', 'name')
    op.drop_column('doctors', 'phone_number')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'name')
    op.drop_column('clients', 'age')
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###
