"""add doctor client realtionship

Revision ID: a339764f02c9
Revises: 33a1dec617b0
Create Date: 2023-08-15 18:23:58.005602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a339764f02c9'
down_revision: Union[str, None] = '33a1dec617b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clients_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clients_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
